### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#16]

**Comment by JordanHolland** [comment]
First pass of this done, will do another for better language later

**Comment by JordanHolland** [comment]
Ok, did a grammar pass. Pretty happy with basic usage functions mentioned. At some point should probably mention that we pass arguments to AutoGluon as well.

**Comment by jesteria** [comment]
Cool. Looks good. Feel free to close this if it's good for now, (or leave it open if you like).
