### ISSUE TITLE
basic test coverage

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#18]

**Comment by JordanHolland** [comment]
I think it's best if we meet in the middle here. I've set up two tests, a single PCAP test and a directory test.

First, a PCAP test:

`nml -a index -L labels.txt -P test.pcap -4 -t`

I ran it from [this directory](https://github.com/nprint/nprintML/tree/main/test/data/single_pcap_test), which contains the labels and the single pcap.

should take about 15 seconds to run.

Second, a directory test:

`nml -a pcap --pcap_dir pcaps/ -L labels.txt -4 -t`

Takes ~8 ish seconds to run.

Ran from [this directory.](https://github.com/nprint/nprintML/tree/main/test/data/pcap_dir_test)
