### ISSUE TITLE
parallelization of nPrint calls

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#26]
It should be possible to speed up the nPrint step by invoking the subprocesses in parallel.

For example, the existing `--threads` flag could be made global, and applied to both AutoML and to nPrint calls.

**Comment by JordanHolland** [comment]
We should definitely share the threads flag for both AutoML and nPrint. AutoML is going to do it's own threading. We're using subprocess as is, should we just use `Pool` from `multiprocessing`?

**Comment by jesteria** [comment]
So long as we invoke nPrint thru a system call (rather than say via a
Python C extension), we're forking the process via `subprocess`. There is a
trend online anyway to suggest using thread or process pools to manage
these system calls; but, while convenient, I'm pretty sure this wastes
processes (and likely degrades efficiency) – you're forking twice as much
as you need.

I've already put together a draft of what I think will be an efficient
implementation of the appropriate "subprocess pool" 👍
