### ISSUE TITLE
filter and drop on loaded nPrints

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#27]
in many cases it is useful to either drop certain fields (ip addresses, ports, etc), or only use specific fields in the representation. This is composed of 4 parts

1. filter function on loaded nPrint dataframe. we can leverage [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.filter.html).
2. flag for filtering
3. drop function on loaded nPrint dataframe. again we can leverage [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)
4. flag for dropping columns.

**Comment by jesteria** [comment]
This will now be based on the feature implemented into nPrint itself – merely exposing the new flag(s).
