### ISSUE TITLE
Attach labels to nPrints before running to save work

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#29]
We need to find a way to attach labels to PCAPs / nPrints *before* running nPrint on every file in the directory. This will save us work on missing labels and allow users to run on subsets of a directory by just supplying new labels. Not entirely sure at the moment where this should be done.

**Comment by jesteria** [comment]
This seems doable by simply checking the labels data before running nPrint on a PCAP.

Granted, I'm not immediately sure how this should look – the current pipeline design presumes that Step 1 (nPrint) won't have to look ahead at the work of Step 2 (labeling). But we can work something out.

**Comment by jesteria** [comment]
On second thought, I was already planning to add something like a `__pre__` method to `Step`, to take care of immediate post-argument parsing tasks, which needn't be postponed until their step in the pipeline, and which can't have dependencies on each other &ndash; like sophisticated validations.

It wouldn't be too much of a stretch to have the `Label` step pre-load labels there, such that they're available at pipeline-start. (And the `Net` step could if really necessary state its dependency on labels explicitly, in `__requires__`, so long as `Label` _also_ specified this in `__provides__` or in something like a `__pre_provides__`.)

**Comment by JordanHolland** [comment]
Preloading the labels at pipeline-start makes sense, it's not going to slow things down. Alternatively, to the above comment, does it make sense to make Step 1 labeling and Step 2 nPrint (reversing how it works now)?

**Comment by jesteria** [comment]
We could reverse the steps, yes; though, we'd still have to put
merging/joining/aggregation (attaching labels) *somewhere*, right?

Definitely worth considering, tho (very initially) I'd lean towards keeping
the step order as it is.

**Comment by jesteria** [comment]
This is in progress.

* `Step.__pre__` has been implemented for this work, (and which will likely be useful for other issues that subvert the pipeline).
*  `LabelAggregator` has been refactored to permit eager ingestion of labels.
