### ISSUE TITLE
write feature dataframe to disk by default

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#30]
The full feature dataframe (NPT+labels) should be written to disk by default, (in addition to passed off to AutoML in memory), for easy inspection and reuse.

This might be optionally disabled by a CLI flag.

**Comment by JordanHolland** [comment]
This seems as simple as adding the CLI flag and doing a `.to_csv()` on the dataframe. We should make sure that we write to gzipped files by default, probably for everything.
