### ISSUE TITLE
Config Output

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#37]
Feature request that makes some sense.

It makes some sense to output a small config file that nPrint and autoML was called with. Not entirely sure what this looks like, but something like

`nPrint configuration: -4 -t -u ...`
`AutoML configuration: number of threads, metric optimized for, ...`

While this could be encoded in an output directory, it's probably best to leave a tiny file that summarizes this

**Comment by jesteria** [comment]
I think that makes sense, even just as a document of where output came from, (for reproduction for example).

We could write this to the top level of the output directory.

**Comment by JordanHolland** [comment]
Let's output a `nprintML.cfg` file at the top level of the output directory. Do we want to be able to read something like this back in to set flags or should this just be for the user's information?
