### ISSUE TITLE
skip and report bad PCAP files (errors)

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#38]
Right now if a PCAP is malformed we bail out on the entire run. It's likely much better to keep track of these errors and report a magnitude and percentage of errors we saw, bailing on the run after a certain percentage.

Looking at the code, this doesn't seem that hard of a feature to pop in to the thread pool that runs each process.

**Comment by jesteria** [comment]
Yep. In summary, we need to:

1. Ensure that these PCAP ingestion errors are usefully reported (in case they are not) (perhaps depending on verbosity setting of course)
2. Continue despite errors; (perhaps give up after a certain number but perhaps not; _n.b._ percentage may not be feasible in so far as input directory trees aren't pre-walked/counted).
3. Ensure that reporting doesn't flood logging/stdout (perhaps unless verbosity is at a particularly high level) – truncate reporting to a certain number (_e.g._ print the first few and the last few only, with an ellipsis or something representing any that are unreported)
4. Log a summary of successes/failures.

**Comment by JordanHolland** [comment]
Is this done with the latest PR?

**Comment by jesteria** [comment]
In that latest PR I believe it's now catching errors silently. This may be an improvement for some users; but, I think that the labeling step only reports PCAPs missing labels, (not the other way around). We should decide what to do in that PR separately, and make sure that this handling & reporting is given proper consideration on its own.

**Comment by jesteria** [comment]
This was ultimately handled, at least to the extent of resolving the core issue, by that latest PR #53 [[code ref]](https://github.com/nprint/nprintML/pull/53/files#diff-4b42bf8bdcbc80d6a3ba1701040ddeb073e52f74fc247b8c999fa4f7be26a125R359).

As a result, users should see any nPrint STDERR (as this isn't captured), and nPrint (PCAP) errors do **not** interrupt the stream.

The reporting is still more bare-bones than what's discussed in this issue; the total count of such failures is simply reported at the end. If we'd like to improve this (and perhaps we should), we can do so, either in fulfillment of this issue or a subsequent one.

(I'll leave this issue for the moment, and we can decide whether to close it / replace it. Regardless, I'd say this is no longer "high priority.")

**Comment by JordanHolland** [comment]
I actually think that the total count of failures and implementation of STDERR for nPrint is enough for now. We can replace this issue down the road if necessary, but my gut is that majority of people will restart runs with failures as is.
