### ISSUE TITLE
AutoGluon API change

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#45]
Marking this even though we've talked in private. AutoGluon API change means that we'll need to change a few imports and the `Predictor` creation code. Text from AutoGluon announcement:

> Announcement for previous users: The AutoGluon codebase has been modularized into namespace packages, which means you now only need those dependencies relevant to your prediction task of interest! For example, you can now work with tabular data without having to install dependencies required for AutoGluon's computer vision tasks (and vice versa). Unfortunately this improvement required a minor API change (eg. instead of from autogluon import TabularPrediction, you should now do: from autogluon.tabular import TabularPredictor), for all versions newer than v0.0.15. Documentation/tutorials under the old API may still be viewed for version 0.0.15 which is the last released version under the old API.

New API: `
from autogluon.tabular import TabularPredictor`

**Comment by jesteria** [comment]
1. It looks like the TabularPrediction API has also changed a bit. We'll have to ensure we're doing what's "right" in addition to what continues to "just work."
2. This should mean significant speed improvements in package building/installing and in process start-up (most noticeable when just calling `--help`).
