### ISSUE TITLE
document AutoGluon optional modeling dependencies | README Update

### ISSUE THREAD

**Issue by JordanHolland** [nprint/nprintML#51]
We've switched to **not install** all of Autogluon's available models (that it just leverages other packages for). We should decide if this is the best idea (it probably is) and if so, I will write some documentation that this is the case and they will need to be installed separately.

**Comment by JordanHolland** [comment]
Left a note in the README that we don't install by default, and that Autogluon is the place to find them.

**Comment by jesteria** [comment]
FYI: I edited this a lil' bit: a6d32e44279be037521927daa1ef9023e67234ec
