### ISSUE TITLE
optimized saving/writing of features

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#55]
Simply serializing & writing the features data to disk appears to be its own bottleneck.

There are likely a number of ways around this and some additional investigation is likely warranted.

However, it appears likely that this could be significantly improved without (as yet) significant effort – _e.g._ by serializing to a more useful and performant format than CSV.

**Comment by jesteria** [comment]
## Feather

[pyarrow.feather](https://arrow.apache.org/docs/python/feather.html)
[also…](https://arrow.apache.org/docs/python/pandas.html)

[pandas.DataFrame.to_feather](https://arrow.apache.org/docs/python/pandas.html)
[pandas.read_feather](https://pandas.pydata.org/docs/reference/api/pandas.read_feather.html)


## csv.gz

(all multi-threading)

* [mgzip](https://pypi.org/project/mgzip/)
* [xopen](https://pypi.org/project/xopen/)
  * [pigz](http://www.zlib.net/pigz/)
* [pigz-python](https://github.com/nix7drummer88/pigz-python/)
* [the stack](https://stackoverflow.com/questions/42867930/how-does-one-achieve-parallel-gzip-compression-with-python)


## otherwise…

…background thread? (_might_ make sense regardless for such things, tho depends.)

**Comment by JordanHolland** [comment]
background thread makes sense to me regardless of the format we're writing to. I tried feather with a dataframe and failed with pandas, but it was probably me.

What seems best to me is 
1. background thread so we can move to learning
2. pandas to feather and read feather to enable anyone to load / read without moving outside of pandas

**Comment by jesteria** [comment]
## Output Format Benchmarking

Using a 1.2 GB features DataFrame (160,571,889 elements) the following approximate performance characteristics were measured.

Output type | Output method | Time (real seconds) | Artifact size (MB)
---------------- | ------------------- | --------------------------- | -------------------------
CSV (uncompressed) | `DataFrame.to_csv('features.csv')` | 53 | 453
CSV-gz |  `DataFrame.to_csv('features.csv.gz')` | 60 | 2
CSV-gz (multithread) | `with mgzip.open…` | 60 | 2
Feather (default: lz4) | `DataFrame.to_feather('features.fhr', compression='lz4')` | 2 | 35
Feather (zstd) | `DataFrame.to_feather('features.fhr', compression='zstd')` | 2 | 18
Parquet | `DataFrame.to_parquet('features.parquet')` | 4 | 25

Above, you can see that there's a slight time overhead to GZIP compression; however, uncompressed CSV stands out as the worst, in that it consumes nearly 0.5 GB of space on disk, and still takes nearly as long to write as CSV.GZ.

CSV.GZ stands out as affording the best compression on disk; though, it does so at the cost of the very worst speed.

Multithreaded writing of GZIP makes absolutely no difference in speed (as anticipated).

Feather does even better than hoped in speed – we were spending around a minute writing such data to CSV or CSV.GZ – and regardless of compression scheme, Feather only takes 1-2 seconds.

Feather's compression isn't quite as robust as hoped and it loses out to CSV.GZIP on this. However, between Feather's speed, ease of use (no worse than CSV as far as users need be concerned), and type support, I think it makes more sense as nprintML's default.

(Note: I also threw in Parquet. We can support this too … though it doesn't appear to do any better than Feather.)

## To do

### Here

- [ ] Support a selection of output file types beginning with: csv, csv.gz, parquet.snappy, parquet.brotli, parquet.gzip, fhr.lz4, and fhr.zstd (default)

### Elsewhere

- [ ] Look into background job queue for performing such tasks on a separate thread while the pipeline proceeds

**Comment by JordanHolland** [comment]
Wow. Not sure much more needs to be said.
