### ISSUE TITLE
command alias

### ISSUE THREAD

**Issue by jesteria** [nprint/nprintML#6]
As a user of nprintML, I would like a command that both makes sense to me and that is easy to type (and tab-complete).

`nprintml` makes sense as a command name and as a project name. However:

* its tab-completion conflicts with that of `nprint` (which must also be present on my system)
* there's nothing particularly "network-print"-y about what I'm doing with `nprintml`

This is not a pressing issue. Nor need the existing nomenclature be revised.

An **alias** could be added for the `nprintml` command, however, (also installed by `pip`), such that invoking the program may also be as simple as typing (and/or tab-completing) something like:

    nml

(or any other).

**Comment by jesteria** [comment]
@JordanHolland: This is far from pressing and fairly speculative, but I thought I'd get the idea written down, for perusal.

**Comment by JordanHolland** [comment]
`nml` makes sense, its actually what I named my virtual environment for the project :).
