### ISSUE TITLE
nprint-install custom pcap directory

### ISSUE THREAD

**Issue by aslacour** [nprint/nprintML#69]
I have installed nprintML in a Conda environment and have also installed libpcap in this environment and was wondering if there was a way to point the nprint-install command to this installation of libpcap? I know the directories containing the pcap.h file and libcap.a file.

**Comment by jesteria** [comment]
Hello! While that isn't a setup I've tested, it sounds like it should work without issue.

…Have you tried simply invoking `nprint-install` as is? Is there some issue with what it does?

Regardless, the command's `--help` flag should also be … helpful:

1. It will tell you where the command thinks it should install `nprint` by default (without arguments), _e.g._:
    > For the current invocation and without options nPrint will be installed by default into the same environment as nprintML (…).
2. It also documents the command's option flags. If you wish to install `nprint` in a custom location, it should be as simple as:
    ```sh
    nprint-install --prefix=…
    ```

HTH!

Please update us on how it goes.

**Comment by aslacour** [comment]
Hello!

I am trying to install `nprint` in the default environment which is the same environment as `nprintML`. When I invoke `nprint-install`, it says I am missing the dependency `pcap`. I believe I have this dependency installed, it is just in a different directory than what the command is looking for. When I force the install, it fails when it can't find `pcap.h`. I know where this file is, so is there some part of the install script I can edit to point it to the location of pcap.h and the rest of the dependency?

**Comment by jesteria** [comment]
Ah hah! Well, we can work with that.

1. Again, if you take a look at `nprint-install --help`, you'll see the `-f` / `--force` flag: "ignore dependency errors". This will install nPrint without checking for libpcap.
2. This command checks for nPrint dependencies with the simple command: `whereis [lib]`. In practice, this is:
    ```sh
    whereis argp pcap
    ```
    If the above doesn't return the path for either argp or pcap, that's perceived as a problem.

However, depending on the system, `whereis` does indeed fail. IIRC, for example, OS X's `whereis` is more easily confused than Linux's. And I wouldn't be surprised if Conda has made it more complicated to check for dependencies as well.

(Speaking of which – are you on OS X? Linux? …?)

It sounds like your way forward is simply to invoke the command as:

```sh
nprint-install --force
```

(And the above assumes that the command's guess for "prefix" is correct. If not, you can set this with one of its other option flags.)

If this successfully installs nPrint and `nprint` works correctly in your environment, then perhaps there is also a smarter way in which `nprint-install` could inspect Conda environments … ?

**Comment by jesteria** [comment]
It's not clear if this was sufficient to resolve the issue – feel free to re-open as necessary!
