### ISSUE TITLE
"Killed" error

### ISSUE THREAD

**Issue by cmarkle85** [nprint/nprintML#70]
I'm just getting started with nPrint and nPrintML. I have gotten nPrint to work however nPrintML is throwing an error - 

> root@bmcoptimization-0:/home/jovyan/nprint/example# nprintml -a index -L labels.txt -P allports.pcap -p 30
> step:Net → NetResult(nprint_stream=(PrimedIterator: <generator object Net.generate_npts at 0x7ff69c265990>))
> Loading nPrint: <NamedBytesIO: allports.npt>
> Loaded 1 nprint
>   nPrint shape: (4921, 240)
> Loading labels: labels.txt
>   number of labels: 4921
> Attaching labels to nPrints
> Killed

From the above command: "allports.pcap" is a pcap file created from merging the port443.pcap and port80.pcap files from the nPrint repo.

So far I have confirmed nprint is working correctly and so is AutoGluon. I have tried running nprintml against just port80.pcap, this threw warnings that there was only 1 label but still ended with "Killed". I have tried a number of different flag combinations without change. I have tried uninstalling and reinstalling through pip. I can also confirm that this is not a RAM issue (I have 16 GB).

I'm running this in an Ubuntu 18.04.5 container with python 3.6.9.

Any help would be appreciated.

**Comment by JordanHolland** [comment]
Hi! 

A few questions.

1. How did you merge the traffic captures?
2. Classification with only one class isn't very useful, AutoGluon (or us) may be failing due to this.
3. Can you show your label file?

Thanks!

**Comment by cmarkle85** [comment]
> Hi!
> 
> A few questions.
> 
> 1. How did you merge the traffic captures?
> 2. Classification with only one class isn't very useful, AutoGluon (or us) may be failing due to this.
> 3. Can you show your label file?
> 
> Thanks!

1. I merged the pcap files using the mergecap utility from wireshark.
2. The single label issue is definitely an issue, however, the "Killed" message appears whether I use allports.pcap or port80.pcap. I was just trying the single label situation to test whether it had something to do with mergecap.
3. I have attached the labels file.

[labels.txt](https://github.com/nprint/nprintML/files/7154702/labels.txt)

**Comment by JordanHolland** [comment]
Can you run with `-tb` to get the traceback when you run it?

The most likely problem is that the labels are causing an issue. In index mode labels are attached to the nPrint index, which by default is the source IP address. There are only 2 IP addresses in the traffic, but we have 4921 separate labels (we probably only want 2?) I should be able to test this shortly.

**Comment by jesteria** [comment]
To be sure, what @JordanHolland is suggesting would be your same command but with the `--tb` or `--traceback` flag, _e.g._:

```sh
nprintml --traceback -a index -L labels.txt -P allports.pcap -p 30
```

---

As for the exception, I couldn't yet say what's at issue either. But I will say that "Killed" almost always means that the program was killed by the system because it exceeded a resource limitation. In my experience that's always been RAM – and 16 GB might seem like a lot, but I've certainly needed more than that. (And as for nprintML, it was recently made **much** more resource efficient during labeling; but, it's still a question of how much data you're trying to label.) Beyond that, particularly if you're using a container, nprintML might be placed under more strict resource limitations than you'd otherwise expect. (I'll assume that you're running your container without RAM constraints, beyond those of the host machine; but, bear in mind that containers are often executed with strict RAM limits, *etc*.)

The traceback flag should help. But diagnosing a resource error limitation might require more system knowledge. 

If you're using Docker, you might be able to monitor the container's basic stats with:

```sh
docker stats [container]
```

And/or within the container or on the host machine you can monitor RAM, *etc.*:

```sh
vmstat 600
```

**Comment by cmarkle85** [comment]
@jesteria,

Thanks for jumping in. I haven't had a chance to run the command with -tb but I don't think I need to anymore. I was fiddling with the environment and reinstalled everything in a larger container (230GB RAM). Keep in mind that the allports.pcap is only 4.1MB. When I ran it this time, the error didn't come up; RAM usage shot up to ~50GB. The following was the output:

> step:Net → NetResult(nprint_stream=(PrimedIterator: <generator object Net.generate_npts at 0x7f46e617fbf8>))
> Loading nPrint: <NamedBytesIO: allports.npt>
> Loaded 1 nprint
>   nPrint shape: (4921, 240)
> Loading labels: labels.txt
>   number of labels: 4921
> Attaching labels to nPrints
>   labels attached: missing labels for:
>     missing labels caused samples to be dropped: -6238554
> step:Label → LabelResult(features=                payload_bit_0  payload_bit_1  ...  payload_bit_239        label
> 174.25.186.210             -1             -1  ...               -1  unencrypted
> 174.25.186.210             -1             -1  ...               -1  unencrypted
> 174.25.186.210             -1             -1  ...               -1  unencrypted
> 174.25.186.210             -1             -1  ...               -1  unencrypted
> 174.25.186.210             -1             -1  ...               -1  unencrypted
> ...                       ...            ...  ...              ...          ...
> 74.70.77.194               -1             -1  ...               -1    encrypted
> 74.70.77.194               -1             -1  ...               -1    encrypted
> 74.70.77.194               -1             -1  ...               -1    encrypted
> 74.70.77.194               -1             -1  ...               -1    encrypted
> 74.70.77.194               -1             -1  ...               -1    encrypted
> 
> [6243475 rows x 241 columns])
> AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
> 	If 'binary' is not the correct problem_type, please manually specify the problem_type argument in fit() (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
> AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
> ^C

The number of rows is way off. My command and/or labels file must be incorrect. It was my understanding that using "-a index" means that you are labeling each row in the nprint and that the corresponding labels file should by structured such that each row in the labels file corresponds to a row in the nprint.

If the above is not correct, please advise on how can nPrintML to generate a model where each row in the nPrint is a record. None of the fields in the nPrint are unique - a single source IP will correspond to multiple rows in the nPrint and possibly different labels for each row.

If my objective is unclear - I'm trying to reproduce your example from the nPrint repo using nPrintML rather than sci-kit learn.

**Comment by JordanHolland** [comment]
Alright, sorry it took a while to get to this, having major troubles getting my development environment set back up. The usage is slightly off, it looks like we haven't done a great job of explaining the "index" functionality of nPrintML (less used than per-file samples). 

With `index`, we are essentially performing a join of the labels and the nPrints based off of the Item column in the label file and the index set in the nPrints (1st column). As such, it isn't one label per row for the index functionality of nPrintML, but one label per item in the index column.

The label file below enables nPrintML to run without error on the `allports.pcap` file you are working with.

```
Item,Label
244.106.52.188,encrypted
74.70.77.194,encrypted
74.189.204.184,encrypted
243.186.23.169,unencrypted
35.14.245.95,unencrypted
238.4.62.5,unencrypted
174.25.186.210,unencrypted
248.55.22.6,unencrypted
48.171.190.166,encrypted
```

Running ` nprintml -a index -L labels.txt -P allports.pcap -p 30` works, and a single source IP can respond to multiple row in the input. As for supplying multiple labels for the same index (source IP in this case), we currently do not have that functionality supported through the `index` flag. If you need this functionality, you could split the traffic into multiple PCAPs and use the `pcap` aggregator. I hope this got us going in the right direction

**Comment by cmarkle85** [comment]
@JordanHolland ,
Thanks that's a big help.

As for the suggestion at the bottom of your comment:

> If you need this functionality, you could split the traffic into multiple PCAPs and use the pcap aggregator.

Are you suggesting creating 1 PCAP file per packet?

**Comment by JordanHolland** [comment]
In this case, if you had different labels for the same index (IP address), it would require 1 PCAP file per packet. Although this is an extreme case (1 file per packet), this is an easy way to use nPrintML for a wide range of use cases:

1. split traffic into PCAPs, 1 group of packets (flow, application, etc) per PCAP.
2. create a label file mapping each PCAP file to a label
3. run nPrintML with the `-pcap` aggregator, which will run nPrint on each individual file and consider each resulting nPrint a single sample for machine learning purposes.

**Comment by cmarkle85** [comment]
@JordanHolland ,
Thanks. I think that addresses all my questions.
