### ISSUE TITLE
nPrintML - brew libomp

### ISSUE THREAD

**Issue by ssgu321** [nprint/nprintml#71]
I am on MacOS Big Sur 11.6, with the M1 2020 chip. I installed nPrintML and nPrint, and I am running the test command on the readme -- `nprintml --ipv4 --pcap-file test.pcap --label-file labels.txt --aggregator `

However, I receive this 

```Detailed Traceback:
Traceback (most recent call last):
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 911, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 883, in _train_single
    model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py", line 405, in fit
    self._fit(**kwargs)
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 110, in _fit
    try_import_xgboost()
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/autogluon/core/utils/try_import.py", line 81, in try_import_xgboost
    import xgboost
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster, DataIter
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/core.py", line 203, in <module>
    _LIB = _load_lib()
  File "/Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/core.py", line 181, in _load_lib
    raise XGBoostError(
xgboost.core.XGBoostError: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ['dlopen(/Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']

	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install fastai==1.*`. If you are using Mac OSX, please use this torch version to avoid compatibility issues: `pip install torch==1.6.0`.
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/soniagu/vms/nprint/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/soniagu/vms/nprint/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

Segmentation fault: 11 
```

I have run `brew install libomp` as well as `python -m pip install lightgbm`, but I still get these errors. I'm pretty sure it's due to the Apple M1 chip as I was having similar[ install issues with brew on nPrint](https://github.com/nprint/nprint/issues/27). Homebrew installs libomp in /opt/homebrew/Cellar/libomp/13.0.0/lib/libomp.dylib instead of /usr/local/opt/libomp/lib/libomp.dylib.

**Comment by jesteria** [comment]
Ah, yeah, this is a new one. From what I can tell this is 100% about xgboost on OSX with M1.

Just to start, I'm curious, did you try reinstalling the Python librar(y|ies) after brew-installing libomp?

Also, shouldn't Homebrew put symlinks into `/usr/local/opt/`? These should link to the libraries under `/opt/homebrew/Cellar/`, (but yes downstream libraries should be compiled against the symlinks in `/usr/local/opt/`).

**Comment by ssgu321** [comment]
Just to clarify, do you mean the Python packages? I tried pip uninstalling and reinstalling the nprintml/xgboost/catboost/lightbgm packages after brew installing libomp, but I received the same error. 

Also, I don't have a 'opt' folder inside the `/usr/local `directory.

**Comment by jesteria** [comment]
Ok. This sounds like a pretty bizarre issue with Homebrew, is all. 

To troubleshoot you might try just creating the symlink that the library appears to expect:

```sh
sudo mkdir -p /usr/local/opt/libomp/lib/
sudo link -s /opt/homebrew/Cellar/libomp/13.0.0/lib/libomp.dylib /usr/local/opt/libomp/lib/libomp.dylib
```

If that happens to do the trick, then great. 

But as for Homebrew and `libomp`, we're really getting out of scope…. This might be a bug in Homebrew. Or perhaps there was an error when you installed Homebrew or when you installed `libomp`. The nprintML traceback you've shared only appears to indicate an issue with Homebrew, but not what precisely this issue might be. 

I believe you can test your Homebrew installation with a command like `brew doctor`.

Regardless, let us know how that goes.

**Comment by ssgu321** [comment]
I created the symlink using the calls above, but it recognizes the wrong architecture:

`Error message(s): ['dlopen(/Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/soniagu/vms/nprint/lib/python3.8/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: no suitable image found.  Did find:\n\t/usr/local/opt/libomp/lib/libomp.dylib: mach-o, but wrong architecture\n\t/usr/local/opt/libomp/lib/libomp.dylib: mach-o, but wrong architecture']`

**Comment by jesteria** [comment]
Ok. Again, I'm just Google searching here to try to help with these libraries on Apple M1 😅 But it appears we might be getting somewhere. 

1. We're still not entirely sure what's up with your Homebrew installation. But it sounds like the manual symbolic link helped. 
2. It sounds like xgboost doesn't support Apple M1. But, [users have reported success compiling it from source](https://github.com/dmlc/xgboost/issues/6909#issuecomment-907587904). 

So having activated your virtual environment:

```sh
pip install xgboost --no-binary xgboost -v --upgrade
```

It sounds like that should prompt your system to compile xgboost from source and resolve the architecture problem. But, let us know!
