### ISSUE TITLE
Running nprintml is really slow for me. Is that normal?

### ISSUE THREAD

**Issue by RicoloveFeng** [nprint/nprintml#77]
### What's up?

The paper of nPrint is really interesting to me, and I installed nPrintML and downloaded the dataset of 100-packet-traffic.

Then I run this command on my WSL:
`nprintml -a pcap --pcap_dir os/ -L os/metadata.csv -4 -t`

However it had taken me more than 70 minutes, and it still kept running on "Loading nPrints" stage.

So I exited the program, deleted most of the data, and kept only first 2000 labels. This time I finished "Loading nPrints" in about one hour, but finally it output an error message and no result was provided:

> No base models to train on, skipping weighted ensemble...
> error:ValueError: AutoGluon did not successfully train any models ✕

I also tried nPrint demo pcap by dividing each port*.pcap into 10-packets pcap. It still took me about 5 minutes to finish "Loading nPrint" even in such a small dataset.

My CPU is i7-10700 with 16GB RAM. But according to the paper, nPrint should have the ability to transform 1m packets per minute even on i7-8559U. So is it normal that "Loading nPrints" costs so much time?

Looking forward to your reply, and your work is really impressive, even though I have no background on network ML, I still appreciate your work. Thank you!

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Hi! Thank you for the detailed issue. I'm on vacation for the next week, just wanted to hop in and say you're not being ignored. 

The one thing I will say is "loading nPrints" is creating a `pandas` DataFrame from all of the create nPrints, so it's likely that nPrint is actually already done running (it does run very quickly), but the data pre-processing before training the models is what is taking up so much time. We (nPrintML) need to do a better job of letting the user know what stage of the pipeline we're on. 

Thank you again for the interest and kind words. I'm going to tag @jesteria on this for this week (if not on vacation) and I can hop on when I get back.

**Comment by RicoloveFeng** [comment]
Thank you for your prompt reply! I have tried to reduce the size of the dataset, and the result was nice for me.

However in a large dataset (e.g. active device fingerprinting), it still took more than 30 minutes before the console showing "step: net -> netResult". But running nPrint independently was indeed faster, so I don't know whether it is a bug of nPrintML, or it is just my low performance device's fault. 

I agree that adding something like process bar or estimated remaining time is a good idea, -VV mode gives too much useless information after all.

Again, thank you for your time and your excellent work. Enjoy your vacation! : )

**Comment by JordanHolland** [comment]
30 minutes does seem like quite a bit of time for that dataset. When I get back I will get a few timings for you on the datasets. Although nPrint is quick, when training models the bigger the machine the better.

Cheers
