### ISSUE TITLE
[Question]: …

### ISSUE THREAD

**Issue by chang-dd** [nprint/nprintml#79]
### What's up?

Hi, author
In this article "new directions in automated traffic analysis", I saw a heatmap of the feature importance, such as Figure 4 in the paper.
I'd like to ask how this figure is obtained and whether to used rf.feature_ importances_ in sklearn this function to draw

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Hello.

[Here](https://github.com/nprint/nprintml/blob/heatmaps/src/nprintml/learn/heatmaps.py) is the old code used to generate the heatmaps. Where the feature importance for each feature comes from ultimately doesn't matter, though in the paper we used the feature importance from the random forest model trained by autogluon. 

Note that the above code is over a year old and need minor tweaks to work with any newer autogluon changes. 

Cheers
