### ISSUE TITLE
leaderboard.csv & stat-report.csv

### ISSUE THREAD

**Issue by aqiu9** [nprint/nprintml#80]
### What's up?

Hi, I have some questions about this couple of CSV files.

I've run nprintml successfully and he generated a folder named nprintml/run-manatee-1648389395-66989. 
In the "model" directory of this folder, I got:
![image](https://user-images.githubusercontent.com/51012896/160522202-82689305-478a-47f4-81a3-debd99414e1a.png)
I think the results may be in the CSVs, are they? If so, could you tell me what the concrete meaning of these CSVs are verbosely and what about their fields？(I'm a student maybe with a limited level and I've read the paper and docs but still keep these questions)

![image_141](https://user-images.githubusercontent.com/51012896/160524700-fce25531-01a5-4b8c-a62f-d4cdf2917475.png)
![image_142](https://user-images.githubusercontent.com/51012896/160524702-d3cf4470-60d2-4c20-9930-5aea7cc46cb2.png)

Thanks a lot!! Have a nice day^v^.

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Hello, 

Thanks for the details included.

nPrintML uses `Autogluon` AutoML to train models. `Autogluon` trains a variety of models on the task, the results of which are seen in `leaderboard.csv`. These results give detailed information about fit time, prediction time, and performance on the test set. The `leaderboard.csv` file is created by `Autogluon`.

The `stat_report.csv` is created by `nprintml`. We take the best performing `Autogluon` model (typically a weighted ensemble of multiple models, and is chosen by `Autogluon`) and calculate a number of standard performance statistics on the test set using the best model. This file is created to aid in presenting results, as the statistics included in `stat_report.csv` are ones typically included in results tables in papers / presentations (such as the ones in the paper).

Cheers

**Comment by aqiu9** [comment]
Thank you for the reply! 
Now I know both of two files better(∩_∩).  

I also want to know if we can find the model file presented by stat_report.csv. Which one?
What does the field "score*" in leaderboard.csv represent? What score?
And fields like "*_test" and "*_val", what's the difference between them? (such as score_test and score_val)

That's all.
Really thank you for taking the trouble to reply!!!
Best wishes

**Comment by JordanHolland** [comment]
> I also want to know if we can find the model file presented by stat_report.csv. Which one?

[loading models](https://auto.gluon.ai/stable/api/autogluon.task.html?highlight=load#autogluon.tabular.TabularPredictor.load)

> What does the field "score*" in leaderboard.csv represent? What score?
> And fields like "_test" and "_val", what's the difference between them? (such as score_test and score_val)

[leaderboard](https://auto.gluon.ai/stable/api/autogluon.task.html?highlight=leaderboard#autogluon.tabular.TabularPredictor.leaderboard)

Also, a handy [cheat sheet](https://auto.gluon.ai/stable/autogluon-cheat-sheet.jpg)

Cheers

**Comment by aqiu9** [comment]
Thanks！
