### ISSUE TITLE
How do I read the results?

### ISSUE THREAD

**Issue by lei-rw** [nprint/nprintml#81]
### What's up?

I found that there are many.pkl files in the result. I tried to read them using pickle's library, but found that only one class is displayed, although there is a lot of content in it. How can I read the relevant information？

### Due diligence

- [x] I have read the docs

**Comment by lei-rw** [comment]
Figure 1 is the result of my running out. I tried to read it with a Python script, as shown in Figure 2. But discovery presents only limited information. I tried to read it with Notepad, but couldn't understand what it was, as shown in Figure 3. Could you please tell me exactly what is in these PKL files and how I can read them?
![figure 1](https://user-images.githubusercontent.com/103157078/162336000-faf3f842-04ed-4eef-b6b0-d234edeb4d57.png)
![figure 2](https://user-images.githubusercontent.com/103157078/162336028-8c728db7-35e8-402d-bbc5-8fb9276feedd.png)
![figure 3](https://user-images.githubusercontent.com/103157078/162336091-556e5706-d57a-4ae5-b6a7-9741fad72c89.png)

**Comment by lei-rw** [comment]
Figure 1 is the result of my running out.
![figure 1](https://user-images.githubusercontent.com/103157078/162336222-8658d57a-49cd-4140-a41e-08431f6daa8e.png)
 I tried to read it with a Python script, as shown in Figure 2. But discovery presents only limited information. 
![figure 2](https://user-images.githubusercontent.com/103157078/162336242-4a0719d6-c17f-479f-997a-c43fc9eb703d.png)
I tried to read it with Notepad, but couldn't understand what it was, as shown in Figure 3. Could you please tell me exactly what is in these PKL files and how I can read them?
![figure 3](https://user-images.githubusercontent.com/103157078/162336251-b38ea956-8aa3-4ca1-be62-44c082255930.png)

**Comment by lei-rw** [comment]
There is also this file 'feature. FHR', I do not know how to read and process it.
![Uploading 屏幕截图 2022-04-08 080925.png…]()

**Comment by lei-rw** [comment]
There is also this file 'feature. FHR', I do not know how to read and process it.
![屏幕截图 2022-04-08 080925](https://user-images.githubusercontent.com/103157078/162339096-5103545d-7c8b-4197-a5f5-709cab2de1f3.png)

**Comment by lei-rw** [comment]
Thank you for your reply!

Figure 1 is the result of my running out.
![figure 1](https://user-images.githubusercontent.com/103157078/162354730-3659037f-3904-40b9-bbba-381211d58730.png)
I tried to read it with a Python script, as shown in Figure 2. But discovery presents only limited information.
![figure 2](https://user-images.githubusercontent.com/103157078/162354749-6322737d-946e-4f35-b3eb-deee65bbbc4f.png)
I tried to read it with Notepad, but couldn't understand what it was, as shown in Figure 3. Can you please tell me how to understand and use these pkl files?
![figure 3](https://user-images.githubusercontent.com/103157078/162354799-7e675283-64c2-4f29-87a3-712f93fe9305.png)

**Comment by JordanHolland** [comment]
Results can be found in the `leaderboard.csv` and  `stat_report.csv`. 

If you are trying to load the model after training: [autogluon reference](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-indepth.html#prediction-options-inference)

If you want to learn more about the files `autogluon` produces: [models](https://auto.gluon.ai/stable/api/autogluon.tabular.models.html), [cheat sheet](https://auto.gluon.ai/stable/cheatsheet.html)

**Comment by lei-rw** [comment]
Thanks, I don't know much about machine learning and thought PKL files were output.

I have another problem, I ran a lot of data sets and often encountered a problem: 'error:ValueError: AutoGluon did not successfully train any models'. As shown in the figure:
![figure 1](https://user-images.githubusercontent.com/103157078/162438879-82856f28-2c87-4e0f-8708-72c73179ed3b.png)
![figure 2](https://user-images.githubusercontent.com/103157078/162438967-fa3e67a8-ff0d-439d-9d74-a0640bfe85ff.png)

But there are not many tips. I want to know what caused that.

**Comment by JordanHolland** [comment]
I can't solve your issue for you, but a few things could be happening:

1. Make sure the `--limit` parameter is changed from the default of 300 to something large, (such as a few hours or more), to give models enough time to train.
2. If the above doesn't fix the problem, see if Autogluon is running out of memory.

**Comment by lei-rw** [comment]
I have also read another paper of yours entitled "Classifying Network Vendors at Internet Scale", to understand the naming rules of data sets. But I don't fully understand it yet. As you can see, 'OFP' in the name indicates a protocol, so what do 'T1', '73', 'TSEQ1' and 'TICMP1' stand for respectively?
![Figure](https://user-images.githubusercontent.com/103157078/162548736-40516c07-e54a-4127-ab85-3d14ffd66bfa.png)
