### ISSUE TITLE
[Question][Updated]: Unable to reproduce the video streaming use case with -c > 15

### ISSUE THREAD

**Issue by VicenteLessa** [nprint/nprintml#91]
### What's up?

Greetings! Firstly, thank you for your insightful work.
I'm a student pursuing a masters degree at INF-UFRGS(Informatics Institute at Federal University of Rio Grande do Sul)
My master's project involves implementing machine learning models on programmable data-planes. 
The stantdard packet representation is a useful concept in this context.  
I'm trying to reproduce the nprintml experiments for many of the use cases.
I was able to sucessfully reproduce the Country of Origin, OS Detection and the Application Identification use cases.
I obtained similar results to those exhibited in the paper "New Directions for Automated Traffic Analysis".

However, I am having problems to reproduce the video streaming use case.
I wanted to execute this video streaming use case with the arguments you provided in the paper, in order to obtain the high accuracy you got in your execution(~98% accuracy with "-c" 50). 
Currently, i can achieve ~84,3% of accuracy in this use case with the arguments -4 -t -u -c 15 -f "tcp[13] == 2".

The first problem is that I can only run nprintml with 15 or less packets (argument "-c" <= 15). 
If i run nprintml with more than 15 packets, I can see the pcaps being loaded (with the verbosity flag -VVV) for a long time, like an hour long, and then the terminal kills the process without even entering the "generating models" phase.
Is this behaviour as expected?
I read that you used 32GB in your experimentations, maybe 24GB of RAM isnt enought? I can see the OS making swap by using the Debian system monitoring tool.
The same problem is happening in the VPN-nonVPN use case (maybe because there are too many pcaps?). 

The second problems happens when using the "-R" argument. The console show an error like this:
"step:Net → NetResult(nprint_stream=(PrimedIterator: <generator object Net.generate_npts at 0x7f0fa40be900>))
Loading nPrints
error:ValueError: Some errors were detected !
    Line #X (got Y columns instead of Z) ✕"
	
	

The datasets were downloaded from the Google drive folder.
I followed the readme instructions to extract the labels csv in all use cases ("pcapml -M traffic.pcapng -O output-dir/").
I'm running Debian 11 with Python 3.8 in a VM with 24GB of RAM and 4 cores of an i5 12400 Processor.

Please, let me know if I'm providing enough information.
Attentiously, John Vincent.

### Due diligence

- [X] I have read the docs

**Comment by VicenteLessa** [comment]
[EDIT]: I was able to execute the video streaming use case with -c argument lower than 15. Also executed Country of Origin, OS Detection and Application Identification use cases. I edited the post to include this infomation

**Comment by JordanHolland** [comment]
So it turns out i didn't have notifications on this repository, I am very sorry about that. These problems, especially with higher packet counts, can require a significant amount of memory. Combine that with training multiple models via AutoML and you are likely running out of memory on higher packet counts.

Again, incredibly sorry this was not ignored, I just never saw it.
