### ISSUE TITLE
[Bug]: python version description is wrong in README.md

### ISSUE THREAD

**Issue by zhangzw16** [nprint/nprintml#93]
### What did you do?

I was trying to install nprintml using `python -m pip install nprintml` in my python 3.9 virtual env. But it always went wrong.

But when i change to python version 3.8, it works alright.

I believe the description that "Python versions 3.7 through 3.9 are supported." was wrong, which should be "Python versions 3.6 through 3.8 are supported.", as in https://nprint.github.io/nprintml/install.html#installation.

### What happened?

```
INFO: pip is still looking at multiple versions of nprintml to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install nprintml==0.0.1, nprintml==0.0.2, nprintml==0.0.3, nprintml==0.0.4, nprintml==0.0.5, nprintml==0.0.6, nprintml==0.0.7 and nprintml==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    nprintml 0.1.0 depends on autogluon.tabular~=0.1.0
    nprintml 0.0.7 depends on autogluon~=0.0.15
    nprintml 0.0.6 depends on autogluon~=0.0.15
    nprintml 0.0.5 depends on autogluon~=0.0.15
    nprintml 0.0.4 depends on autogluon~=0.0.15
    nprintml 0.0.3 depends on autogluon~=0.0.14
    nprintml 0.0.2 depends on autogluon~=0.0.24
    nprintml 0.0.1 depends on autogluon~=0.0.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Operating system

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04

### Version

1.1.2

**Comment by JordanHolland** [comment]
Thanks for the report. My browser and the code show that the descirption says 3.6 - 3.8?

**Comment by zhangzw16** [comment]
<img width="872" alt="Screenshot 2024-01-24 at 10 37 20" src="https://github.com/nprint/nprintml/assets/26004183/4a3e5c32-f667-4533-a79a-79c4f6d23282">

**Comment by JordanHolland** [comment]
Ah, thanks. The README differed from the installation instructions on our website. Thanks for pointing that out, I fixed it!
